# Generated by Django 3.0.8 on 2020-10-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201006_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stu_no',
            new_name='std_no',
        ),
    ]
