# Generated by Django 3.0.8 on 2020-10-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201006_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direction',
            field=models.CharField(blank=True, max_length=10, verbose_name='方向'),
        ),
    ]
