# Generated by Django 3.0.8 on 2020-10-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201020_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag2',
            options={'verbose_name': '文章标签2', 'verbose_name_plural': '文章标签2'},
        ),
    ]
