# Generated by Django 3.0.8 on 2020-10-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201020_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags2',
        ),
        migrations.DeleteModel(
            name='Tag2',
        ),
    ]
